// ═══════════════════════════════════════════════════════
// 🎵 HIMNARIO ADVENTISTA NUEVO — 613 HIMNOS
// Base de datos completa para autocomplete
// ═══════════════════════════════════════════════════════

const HIMNARIO_ADVENTISTA = {
    1: "Cantad alegres al Señor",
    2: "Da gloria al Señor",
    3: "Unidos en espíritu",
    4: "Alabanzas sin cesar",
    5: "A ti, glorioso Dios",
    6: "¡Hosanna!",
    7: "Oh Dios, mi soberano Rey",
    8: "¡Suenen dulces himnos!",
    9: "Alabemos al Señor",
    10: "Alaba al Dios de Abraham",
    11: "Alma, bendice al Señor",
    12: "Todos juntos reunidos",
    13: "Al Dios invisible",
    14: "Engrandecido sea Dios",
    15: "Loámoste, ¡oh Dios!",
    16: "A nuestro Padre Dios",
    17: "Oh Padre, eterno Dios",
    18: "Load al Padre",
    19: "Padre nuestro",
    20: "A Dios, el Padre celestial",
    21: "Gloria sea al Padre",
    22: "Jehová está en su santo",
    23: "¡Silencio! ¡Silencio!",
    24: "Imploramos tu presencia",
    25: "Siento la presencia del Señor",
    26: "Aquí reunidos",
    27: "¡Oh Pastor divino, escucha!",
    28: "Tu pueblo jubiloso",
    29: "Del culto el tiempo llega",
    30: "Abre mis ojos",
    31: "¡Oh, Señor! al orar",
    32: "Nos reunimos en tu santuario",
    33: "Tu presencia, Padre amante",
    34: "En momentos así",
    35: "Oye, oh Señor",
    36: "¡Oh, Dios, que oyes cada oración!",
    37: "Dios os guarde",
    38: "Que Dios te guarde",
    39: "Despide hoy tu grey",
    40: "Shalom",
    41: "Gracia, amor y comunión",
    42: "Queda, Señor",
    43: "Agua de vida",
    44: "Despídenos con tu bendición",
    45: "Después, Señor",
    46: "Hoy amanece",
    47: "Por la mañana",
    48: "Oh Dios, si he ofendido",
    49: "Cristo, ya la noche cierra",
    50: "Nuestro sol se pone ya",
    51: "Señor Jesús, el día ya se fue",
    52: "Señor Jesús, el día ya se fue",
    53: "¡Oh amor de Dios!",
    54: "Tan bueno es Dios",
    55: "Grande, Señor, es tu fidelidad",
    56: "De tal manera amó",
    57: "Mi Dios me ama",
    58: "Grande es el amor divino",
    59: "Mirad qué amor",
    60: "¡Santo! ¡Santo! ¡Santo!",
    61: "Santo, Santo, Santo",
    62: "Santo, Santo, Santo",
    63: "Al Rey adorad",
    64: "Yo canto el poder de Dios",
    65: "El mundo es de mi Dios",
    66: "¿Sabes cuántos?",
    67: "¡Señor, yo te conozco!",
    68: "Todo lo que ha creado Dios",
    69: "Señor, mi Dios",
    70: "¡Nuestro Dios reina!",
    71: "Cada cosa hermosa",
    72: "Fue un milagro",
    73: "La creación",
    74: "Himno al Creador",
    75: "Grande es Jehová",
    76: "Eterno Dios, mi Creador",
    77: "Sea exaltado",
    78: "¡Al mundo paz!",
    79: "Se oye un canto en alta esfera",
    80: "Venid, pastorcillos",
    81: "Noche de paz",
    82: "Ya repican las campanas",
    83: "La primera Navidad",
    84: "Ve, dilo en las montañas",
    85: "Allá en el pesebre",
    86: "A medianoche en Belén",
    87: "Venid, fieles todos",
    88: "Oh, aldehuela de Belén",
    89: "Cristianos, alegraos hoy",
    90: "Somos del oriente",
    91: "¿Qué niño es este?",
    92: "Ángeles cantando están",
    93: "Hubo Uno que quiso",
    94: "Sangró mi soberano Dios",
    95: "Un día",
    96: "Al contemplar la excelsa cruz",
    97: "En el monte Calvario",
    98: "Rostro divino",
    99: "Jamás podrá alguien",
    100: "¡Dulces momentos!",
    101: "Cabeza sacrosanta",
    102: "Cordero de Dios",
    103: "Jesús resucitado",
    104: "La tumba le encerró",
    105: "Cristo ha resucitado",
    106: "Tuya es la gloria",
    107: "Canto el gran amor",
    108: "Amigo fiel es Cristo",
    109: "Un buen amigo tengo yo",
    110: "Cristo es el mejor amigo",
    111: "Como Jesús no hay otro",
    112: "Ningún otro me amó cual",
    113: "Amor que no me dejarás",
    114: "Dime la antigua historia",
    115: "¡Oh, cuán grande amor!",
    116: "Cristo está a mi lado",
    117: "No sé por qué",
    118: "Cuando estés cansado y",
    119: "De su trono, mi Jesús",
    120: "¡Cuánto me alegra!",
    121: "Es Jesucristo la vida, la luz",
    122: "Divino pastor",
    123: "¡Cuánto nos ama Jesús!",
    124: "Ama el Pastor sus ovejas",
    125: "Infinito amor de Cristo",
    126: "Abrigadas y salvas en el redil",
    127: "Cristo, nombre dulce",
    128: "¡Tu nombre es dulce, buen Jesús!",
    129: "Cual Jesús no hay otro",
    130: "Cristo, Cristo, Cristo",
    131: "Bendito es el nombre de Jesús",
    132: "Dulce, hermoso nombre es",
    133: "Venid, con cánticos venid",
    134: "Cual mirra fragante",
    135: "Cristo, nombre sublime",
    136: "¡Oh, cuánto amo a Cristo!",
    137: "De Jesús el nombre invoca",
    138: "De mi amante Salvador",
    139: "La tierna voz del Salvador",
    140: "Te quiero, te quiero",
    141: "¡Alabadle!",
    142: "Venid, cantad de gozo en",
    143: "Digno eres tú",
    144: "Mi Salvador",
    145: "Con acentos de alegría",
    146: "Ni en la tierra",
    147: "A Dios sea gloria",
    148: "Solo Cristo",
    149: "Junto a la cruz de Jesús",
    150: "A Cristo doy mi canto",
    151: "Por eso lo amo",
    152: "A ti, Jesús",
    153: "Ved a Cristo",
    154: "Dad gloria al Cordero Rey",
    155: "En Sion Jesús hoy reina",
    156: "A Cristo coronad",
    157: "¡Majestad!",
    158: "Amanece ya la mañana de oro",
    159: "Yo espero la mañana",
    160: "Viene otra vez nuestro Salvador",
    161: "¡Oh! cuán gratas las nuevas",
    162: "En presencia estar de Cristo",
    163: "Cristo viene, esto es cierto",
    164: "Jesús pronto volverá",
    165: "¡Vendrá el Señor!",
    166: "Siervos de Dios, la trompeta",
    167: "¿Quién en deslumbrante gloria?",
    168: "El Rey que viene",
    169: "Cuando suene la trompeta",
    170: "La segunda venida de Cristo",
    171: "¿Has oído el mensaje?",
    172: "Promesa dulce",
    173: "¿Será al albor?",
    174: "Mira los hitos",
    175: "Ved a Cristo, que se acerca",
    176: "Tú verás al Rey viniendo",
    177: "Los tres mensajes angélicos",
    178: "Contemplé la gloria",
    179: "¡Cristo viene! Aquel día se acerca",
    180: "Sí, lo veremos",
    181: "Una esperanza",
    182: "Veremos a Cristo",
    183: "No me olvidé de ti",
    184: "Nunca te rindas",
    185: "Al cielo voy",
    186: "Hace años escuché",
    187: "Aunque anochezca",
    188: "Gran alegría",
    189: "Cristo muy pronto vendrá",
    190: "Santo Espíritu de Cristo",
    191: "La nueva proclamad",
    192: "Llena mi ser",
    193: "Dios nos ha dado promesa",
    194: "Vive en mí",
    195: "Abre mis ojos a la luz",
    196: "Santo Espíritu de Dios",
    197: "Dulce Espíritu",
    198: "Desciende, Espíritu de amor",
    199: "Movidos por tu Espíritu",
    200: "Bautízanos hoy",
    201: "Canción del Espíritu",
    202: "Danos el fuego",
    203: "Santo Espíritu llena mi vida",
    204: "Oh, cantádmelas otra vez",
    205: "Dadme la Biblia",
    206: "Padre, tu Palabra es mi guía",
    207: "Dios nos habla",
    208: "¡Santa Biblia!",
    209: "La Biblia nos habla de Cristo",
    210: "Huye cual ave",
    211: "Fija tus ojos en Cristo",
    212: "A tu puerta Cristo está",
    213: "Tierno y amante, Jesús nos llama",
    214: "Mientras Jesús te llama",
    215: "Con voz benigna te llama",
    216: "Dios al pródigo llama",
    217: "Bienvenida de Jesús",
    218: "A Jesucristo ven sin tardar",
    219: "Tan triste y tan lejos de Dios",
    220: "Allá la puerta abierta está",
    221: "Puertas abiertas encontrarán",
    222: "Del trono celestial",
    223: "Oí la voz del Salvador",
    224: "Oí la voz del buen Jesús",
    225: "Un hombre llegose de noche",
    226: "Buscad primero",
    227: "Preste oídos el humano",
    228: "Me buscaréis y me hallaréis",
    229: "¿Has pensado que puede acontecer?",
    230: "Abre tu corazón",
    231: "Todo en el altar",
    232: "Entrégate en oración",
    233: "Ven a la Fuente de vida",
    234: "¿Temes que en la lucha?",
    235: "La razón de vivir",
    236: "A Jesús entrégatelo todo",
    237: "Jesús hoy espera entrar en tu corazón",
    238: "Yo escucho, buen Jesús",
    239: "De Dios vagaba lejos yo",
    240: "Te ruego, oh Dios",
    241: "Perdón te ruego, mi Señor",
    242: "Una es, Señor, mi petición",
    243: "Entrégatelo todo a Cristo",
    244: "Padre, Dios",
    245: "Cúmplase, oh Cristo, tu voluntad",
    246: "Te quiero, mi Señor",
    247: "Yo te seguiré",
    248: "Que mi vida entera esté",
    249: "Tal como soy",
    250: "Padre, a tus pies me postro",
    251: "No yo, sino Cristo",
    252: "Dejo el mundo",
    253: "Tuyo soy, Jesús",
    254: "Anhelo ser limpio",
    255: "Oh Cristo, te adoro",
    256: "Jesús, yo he prometido",
    257: "¡Oh! ven, te invito, Cristo",
    258: "Tú dejaste tu trono",
    259: "Mi espíritu, alma y cuerpo",
    260: "Junto a la cruz de Cristo",
    261: "Salvador, a ti me rindo",
    262: "Los tesoros del mundo",
    263: "Entra en este corazón",
    264: "Un día más por Cristo",
    265: "La senda ancha dejaré",
    266: "Vivo por Cristo",
    267: "A la cruz de Cristo voy",
    268: "Puedo oír tu voz llamando",
    269: "Prefiero a mi Cristo",
    270: "Meditar en Jesús",
    271: "Hoy me llama el mundo en vano",
    272: "De esclavitud",
    273: "Tu vida, oh Salvador",
    274: "¿Qué te daré, Maestro?",
    275: "Humilde oración",
    276: "Con nuestras mentes",
    277: "Amarte más",
    278: "¿Puede el mundo ver a Jesús?",
    279: "Transfórmame a tu imagen",
    280: "Ser semejante a Cristo",
    281: "He decidido seguir a Cristo",
    282: "¡Brilla, Jesús!",
    283: "Ven, Señor Jesús",
    284: "Me dice el Salvador",
    285: "Confío en Jesucristo",
    286: "Hay una fuente sin igual",
    287: "Rey de mi vida",
    288: "Al contemplarte, mi Salvador",
    289: "¿Qué me puede dar perdón?",
    290: "Fuente de la vida eterna",
    291: "Perdido, fui a mi Jesús",
    292: "Por fe en Cristo, el Redentor",
    293: "¿Quieres ser salvo toda hora?",
    294: "En Jesús por fe confío",
    295: "Las manos, Padre",
    296: "Comprado con sangre por Cristo",
    297: "Salvado con sangre por Cristo",
    298: "Al Calvario, solo, Jesús",
    299: "Hay vida en mirar",
    300: "Lejos de mi Padre Dios",
    301: "Cristo es mi amante Salvador",
    302: "Grato es contar la historia",
    303: "Sublime gracia",
    304: "Mi Redentor, el Rey de gloria",
    305: "Maravillosa su gracia es",
    306: "Llegó Jesús",
    307: "Roca de la eternidad",
    308: "Dios descendió",
    309: "La voz de Jesús",
    310: "Cristo, centro de mi vida",
    311: "Cuando junte Jesús las coronas",
    312: "Día grande viene",
    313: "La hora del Juicio",
    314: "Cristo Rey omnipotente",
    315: "El juicio empezó",
    316: "Hay un mundo feliz más allá",
    317: "En el hogar do nunca habrá",
    318: "En la mansión de mi Señor",
    319: "Cuando mi lucha termine al fin",
    320: "Jamás se dice adiós allá",
    321: "Allá sobre montes",
    322: "Busquemos la Patria",
    323: "He de conocerle entonces",
    324: "Pronto yo veré a Jesús",
    325: "No puede el mundo ser mi hogar",
    326: "Un día yo he de faltar",
    327: "Jerusalén, mi amado hogar",
    328: "¿Nos veremos junto al río?",
    329: "En la célica morada",
    330: "Hay un feliz Edén",
    331: "La mañana gloriosa",
    332: "En la tierra adonde iré",
    333: "Aunque en esta vida",
    334: "Cuánto anhelo llegar",
    335: "Mi hogar celestial",
    336: "Del bello país he leído",
    337: "Nunca más adiós",
    338: "Las riberas de dicha inmortal",
    339: "A veces oigo un himno",
    340: "¡Oh, qué música divina!",
    341: "Más cerca del hogar",
    342: "Después del río",
    343: "Quiero llegar a ser parte del cielo",
    344: "Entonad un himno",
    345: "Canta, y tus penas se irán",
    346: "¡Feliz el día!",
    347: "Con gozo canto al Señor",
    348: "Dicha grande",
    349: "Gran gozo hay en mi alma",
    350: "Andando en la luz de Dios",
    351: "Yo tengo gozo",
    352: "Gozaos, Cristo es Rey",
    353: "Suenan melodías en mi ser",
    354: "Voy caminando",
    355: "Yo voy feliz",
    356: "Gozo es conocer a Cristo",
    357: "Jesús, tú eres mi alegría",
    358: "En el seno de mi alma",
    359: "Regocilaos siempre",
    360: "En Jesucristo, mártir de paz",
    361: "Percibe mi alma un son",
    362: "Con sin igual amor",
    363: "Hay un canto nuevo en mi ser",
    364: "Jesús da paz",
    365: "Elevemos al Señor",
    366: "En Cristo hallo amigo",
    367: "Gracias, Dios",
    368: "Padre amado",
    369: "Gratitud y alabanza",
    370: "Por la excelsa majestad",
    371: "Jesús te ama",
    372: "¿Cómo agradecer?",
    373: "Mi Redentor es Cristo",
    374: "Dulce comunión",
    375: "Sed puros y santos",
    376: "Dulce oración",
    377: "A los pies de Jesucristo",
    378: "¡Oh, qué amigo nos es Cristo!",
    379: "Habla, Señor, a mi alma",
    380: "Ando con Cristo",
    381: "De mañana veo su faz",
    382: "A solas al huerto yo voy",
    383: "Habla a tu Dios de mañana",
    384: "El jardín de oración",
    385: "Hablando con Jesús",
    386: "Hay un lugar de paz",
    387: "Aparte del mundo",
    388: "Debo decir a Cristo",
    389: "Conversar con Jesucristo",
    390: "Soy yo, Señor",
    391: "¿Le importará a Jesús?",
    392: "Hay quien vela mis pisadas",
    393: "Mi fe contempla a ti",
    394: "¡Cuán firme cimiento!",
    395: "¡Oh, cuán dulce es fiar en Jesús!",
    396: "¡Oh qué Salvador!",
    397: "Oh buen Señor, velada está",
    398: "Cuando sopla airada la tempestad",
    399: "En estos tiempos",
    400: "Castillo fuerte es nuestro Dios",
    401: "Eterna Roca es mi Jesús",
    402: "¡Oh!, salvo en la Roca",
    403: "Cuando en la lucha",
    404: "A cualquiera parte",
    405: "Sé quién es Jesús",
    406: "Jesús es mi luz",
    407: "Muy cerca de mi Redentor",
    408: "Cristo me ayuda por él a vivir",
    409: "Si mi débil fe flaqueare",
    410: "Cuando te quiero",
    411: "Bajo sus alas",
    412: "Todas las promesas",
    413: "Si la carga es pesada",
    414: "¡Oh, buen Maestro, despierta!",
    415: "Salvo en los tiernos brazos",
    416: "¡Oh!, tenía yo la ardiente fe",
    417: "Dame la fe de mi Jesús",
    418: "Padre, yo vengo a ti",
    419: "Por la justicia de Jesús",
    420: "Nunca desmayes",
    421: "Cariñoso Salvador",
    422: "Nada puede ya faltarme",
    423: "Pertenezco a mi Rey",
    424: "¿Cómo podré estar triste?",
    425: "Día en día",
    426: "Tengo paz",
    427: "Lleva todo tu pesar a Cristo",
    428: "Su oveja soy",
    429: "Él puede",
    430: "Solo no estoy",
    431: "A él mis problemas le doy",
    432: "Como el ciervo",
    433: "Conmigo marcha un ángel",
    434: "Jesús es mi vida",
    435: "Dios sabe, Dios oye, Dios ve",
    436: "Él vive hoy",
    437: "Tu presencia, Padre amado",
    438: "Mira hacia Dios",
    439: "¡Oh! quién pudiera andar con Dios",
    440: "Quiero, Jesús, contigo andar",
    441: "Jesús, te necesito",
    442: "¡Oh! ¡Maestro y Salvador!",
    443: "Hay un lugar do quiero estar",
    444: "No me pases",
    445: "Más de Jesús",
    446: "Más cerca, oh Dios, de ti",
    447: "Más santidad dame",
    448: "Salvador, mi bien eterno",
    449: "Cristo, mi piloto sé",
    450: "¡Oh Jesús, Pastor divino!",
    451: "Cerca, más cerca",
    452: "Contigo quiero andar",
    453: "Cómo ser cual Cristo",
    454: "Yo quisiera andar con Cristo",
    455: "Mi mano ten",
    456: "Como la mujer de junto al pozo",
    457: "More en mi belleza del Señor",
    458: "Orad por mí",
    459: "Háblame más de Cristo",
    460: "Quiero estar cerca de Cristo",
    461: "A tu lado anhelo estar",
    462: "Dame a Cristo",
    463: "Mi oración",
    464: "Ven, inspíranos",
    465: "Ven junto a mí",
    466: "Guíame, ¡oh Salvador!",
    467: "¡Siempre el Salvador me guía!",
    468: "Paso a paso Dios me guía",
    469: "Jesús me guía",
    470: "Guíame, Dios",
    471: "Condúceme, Maestro",
    472: "Jesús, mi guía es",
    473: "Háblame, y hablaré",
    474: "¿Qué me importan?",
    475: "El camino es escabroso",
    476: "¡Muy lejos el hogar está?",
    477: "Los que aman al Señor",
    478: "Sé fiel siempre, hermano",
    479: "De la mano, Señor",
    480: "Dime, eres, oh Señor",
    481: "Voy al cielo",
    482: "Quiero cantar",
    483: "Cuando al cielo lleguemos",
    484: "Busca a Jesús",
    485: "Unidos en verdad",
    486: "En los pasos de Jesús",
    487: "Cristo, eres justo Rey",
    488: "Al andar con Jesús",
    489: "Solo anhelo, Cristo amado",
    490: "Mejor que los sacrificios",
    491: "Levántate, cristiano",
    492: "¡Trabajad! ¡Trabajad!",
    493: "Hoy quiero trabajar contigo",
    494: "Cerca un alma agobiada está",
    495: "Mi deber",
    496: "Sus manos somos",
    497: "Manos",
    498: "Puedes demostrar con tus manos",
    499: "Jesús anduvo por aquí",
    500: "Hazme tu siervo",
    501: "Mi vida al servicio de Dios",
    502: "Brilla en el sitio donde estés",
    503: "Oh Dios, que deseas la vida",
    504: "Señor de todos",
    505: "Hijo del reino",
    506: "¡De pie, de pie, cristianos!",
    507: "Tentado, no cedas",
    508: "Contendamos siempre",
    509: "¡Firmes! ¡Fuertes!",
    510: "¿Quién está por Cristo?",
    511: "Marcharé en la divina luz",
    512: "Nunca estéis desanimados",
    513: "Honra al hombre de valor",
    514: "¡Despertad, despertad!",
    515: "Despliégue el cristiano su bandera",
    516: "¡Firmes y adelante!",
    517: "De pie, oh grey de Dios",
    518: "Jesús está buscando",
    519: "Despierta, hermano, sin tardar",
    520: "¡Adelante! manda el Señor",
    521: "Al Cristo ved",
    522: "Suenen las palabras",
    523: "Los sabios dan su ciencia",
    524: "Traían en silencio presentes",
    525: "Con gratitud, llamemos",
    526: "Oh, mi patria, te prometo hoy",
    527: "Señor Jehová, omnipotente",
    528: "Por montañas, muy cansado",
    529: "Iglesia de Cristo",
    530: "Somos un pequeño pueblo",
    531: "La familia de Dios",
    532: "Sagrado es el amor",
    533: "Cuán bueno y agradable",
    534: "En tu nombre comenzamos",
    535: "Las faenas terminadas",
    536: "En sombras de la tarde",
    537: "Sábado santo",
    538: "Hoy es día de reposo",
    539: "¡Oh, día delicioso!",
    540: "Ya asoma el sol brillante",
    541: "Señor, reposamos",
    542: "Amo tu sábado",
    543: "No te olvides del día del Señor",
    544: "Hoy el sábado glorioso",
    545: "Santo día",
    546: "Santo sábado, bendito",
    547: "Sábado",
    548: "Mi corazón se llena de alegría",
    549: "Ya el fin se acerca",
    550: "Día santo del Señor",
    551: "Embajador soy de mi Rey",
    552: "¡Oh!, cuánto necesita",
    553: "¿Os pusisteis a arar?",
    554: "Con Cristo avanza hoy",
    555: "Hoy gozoso medito",
    556: "Yo quiero siempre brillar",
    557: "¿Qué estás haciendo por Cristo?",
    558: "Ama a tus prójimos",
    559: "No dé de temor",
    560: "Cristo está buscando obreros",
    561: "Oigo del Señor la voz",
    562: "Esparcid la luz de Cristo",
    563: "Escuchad, Jesús nos dice",
    564: "Pronto la noche viene",
    565: "¡Ve, ve oh Sion!",
    566: "Centinelas del Maestro",
    567: "Si en valles de peligros",
    568: "Hay lugar en la amplia viña",
    569: "Id y predicad el evangelio",
    570: "Voluntario del Señor",
    571: "La historia de Cristo",
    572: "Pescadores de hombres",
    573: "Te envío a ti",
    574: "Testimonio",
    575: "Tocad trompeta ya",
    576: "Proclamo hoy",
    577: "Yo quiero trabajar",
    578: "El pueblo que conoce a su Dios",
    579: "La fuente veo",
    580: "Las aguas del bautismo",
    581: "El Pan de vida soy",
    582: "Hoy venimos cual hermanos",
    583: "La Cena de la Comunión",
    584: "Amémonos, hermanos",
    585: "De rodillas partimos hoy el pan",
    586: "En memoria de mí",
    587: "Te dedicamos, oh Señor",
    588: "Ven, alma que lloras",
    589: "Perfecto amor",
    590: "Guía a ti, Señor",
    591: "Todo es bello en el hogar",
    592: "Si Dios está, ¡feliz hogar!",
    593: "Hogar de mis recuerdos",
    594: "Señor, gracias por mi hogar",
    595: "Feliz hogar",
    596: "Edificamos familias",
    597: "Oración por un niño",
    598: "Cristo, yo te seguiré",
    599: "En este bello día",
    600: "Cuando leo en la Biblia",
    601: "Cuando venga Jesucristo",
    602: "Es el amor divino",
    603: "Yo temprano busco a Cristo",
    604: "Bellas las manitas son",
    605: "Jesús tiene tiempo",
    606: "Llama Jesús, el Buen Pastor",
    607: "Nítido rayo por Cristo",
    608: "Corazones siempre alegres",
    609: "¡Oh jóvenes, venid!",
    610: "Escuchamos tu llamada",
    611: "Oh, juventud del Rey",
    612: "Jesús te necesita hoy",
    613: "Hoy nos toca trabajar"
};

// Función auxiliar para buscar himno por número
function buscarHimno(numero) {
    return HIMNARIO_ADVENTISTA[numero] || null;
}

// Función auxiliar para buscar himnos por texto
function buscarHimnosPorTexto(texto) {
    if (!texto || texto.length < 2) return [];
    const t = texto.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    const resultados = [];
    Object.entries(HIMNARIO_ADVENTISTA).forEach(([num, titulo]) => {
        const tNorm = titulo.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
        if (tNorm.includes(t)) {
            resultados.push({ num: parseInt(num), titulo });
        }
    });
    return resultados.slice(0, 8);
}

// ═══════════════════════════════════════════════════════
// 🎵 HIMNARIO POR CATEGORÍAS — Para planificación de cultos
// ═══════════════════════════════════════════════════════
const HIMNARIO_CATEGORIAS = [
    { grupo: '⛪ EL CULTO', color: '#a29bfe', cats: [
        { nombre: 'Adoración y Alabanza', ico: '🎶', nums: [1,2,3,4,7,8,14,15,16,17,26,60,128,133,138,141,153,155,156] },
        { nombre: 'Apertura', ico: '🚪', nums: [24,27,28,29] },
        { nombre: 'Clausura', ico: '🙏', nums: [37,39,45] },
        { nombre: 'Matutinos', ico: '🌅', nums: [47] },
        { nombre: 'Vespertinos', ico: '🌆', nums: [48,49,50,51,52,471,535] },
        { nombre: 'Preces (Ruego, Súplica)', ico: '🙇', nums: [6,20,21,22,36,44] }
    ]},
    { grupo: '👑 DIOS EL PADRE', color: '#fdcb6e', cats: [
        { nombre: 'Su Amor', ico: '❤️', nums: [53,57,58] },
        { nombre: 'Su Majestad y Poder', ico: '⚡', nums: [61,63,69,76] },
        { nombre: 'Su Providencia', ico: '🤲', nums: [5] },
        { nombre: 'Su Poder en la Naturaleza', ico: '🌿', nums: [64,65,66,67] }
    ]},
    { grupo: '✝️ JESUCRISTO', color: '#55efc4', cats: [
        { nombre: 'Navidad / Primer Advenimiento', ico: '⭐', nums: [78,79,80,81] },
        { nombre: 'Su Sufrimiento y Muerte', ico: '✝️', nums: [93,94,95,96,97,98,99,100] },
        { nombre: 'Su Resurrección y Ascensión', ico: '🌅', nums: [103,104,105] },
        { nombre: 'Su Alabanza y Gloria', ico: '👑', nums: [129,134,137,140,142,145,147,149,150,154,286,396,397,487] },
        { nombre: 'Su Segundo Advenimiento', ico: '☁️', nums: [158,159,160,161,162,163,164,165,166,167,168,169,170,171,173,230,505] },
        { nombre: 'Su Reino y Señorío', ico: '🏰', nums: [172,316] },
        { nombre: 'Su Amor y Ternura', ico: '💕', nums: [107,108,109,110,111,113,114,118,121,124,126,139,146,210,211,284,366,391,392,407] }
    ]},
    { grupo: '🕊️ ESPÍRITU SANTO', color: '#74b9ff', cats: [
        { nombre: 'El Espíritu Santo', ico: '🕊️', nums: [190,191,193,195,196,198,202] }
    ]},
    { grupo: '📖 SAGRADAS ESCRITURAS', color: '#ff9f43', cats: [
        { nombre: 'La Biblia', ico: '📖', nums: [204,205,206,208,209,394] }
    ]},
    { grupo: '📢 EL EVANGELIO', color: '#ff6b6b', cats: [
        { nombre: 'El Llamado', ico: '📢', nums: [212,213,214,215,216,217,218,219,220,221,222,223,224,227,233,234,238,317] },
        { nombre: 'Arrepentimiento', ico: '😢', nums: [225,239,240] },
        { nombre: 'Fe y Confianza', ico: '🛡️', nums: [246,285,307,393,395,398,400,401,402,403,404,406,408,410,411,412,416,419,474,488] },
        { nombre: 'Consagración', ico: '🔥', nums: [245,247,248,249,250,251,252,253,254,255,256,258,259,260,261,267,272,288,418] },
        { nombre: 'Salvación y Redención', ico: '💉', nums: [185,242,262,263,287,289,290,291,292,293,294,296,298,299,300,301,304,350] },
        { nombre: 'Recompensa de los Justos', ico: '🏆', nums: [319,320,344] },
        { nombre: 'La Vida Eterna', ico: '♾️', nums: [318,321,323,326,334] }
    ]},
    { grupo: '🌟 VIDA CRISTIANA', color: '#00cec9', cats: [
        { nombre: 'Gozo y Paz', ico: '😊', nums: [302,346,347] },
        { nombre: 'Oración y Meditación', ico: '🧘', nums: [23,375,376,378,387,440,441] },
        { nombre: 'El Trabajo y el Deber', ico: '🔨', nums: [264,491,492,494,510,511,515,551,552,553,555,557,558,562,566,575,577] },
        { nombre: 'Lealtad', ico: '⚔️', nums: [266,417,507] }
    ]},
    { grupo: '🏛️ LA IGLESIA Y DOCTRINAS', color: '#6c5ce7', cats: [
        { nombre: 'La Iglesia', ico: '⛪', nums: [529,532] },
        { nombre: 'La Escuela Sabática', ico: '📚', nums: [534] },
        { nombre: 'Ministerio y Misiones', ico: '🌍', nums: [560,561,563,564,565,567,568,571] },
        { nombre: 'La Juventud', ico: '🧑', nums: [351,383,513,518,570,608,609,610,613] },
        { nombre: 'El Bautismo', ico: '💧', nums: [295,579,580] },
        { nombre: 'El Sábado', ico: '🕯️', nums: [537,538,539,540,541,544,545,549,550] },
        { nombre: 'La Cena del Señor', ico: '🍞', nums: [581,582,584] },
        { nombre: 'Diezmos y Ofrendas', ico: '💰', nums: [521,522,524] },
        { nombre: 'El Juicio Final', ico: '⚖️', nums: [311,312] },
        { nombre: 'La Tierra Nueva', ico: '🌈', nums: [325,327,328,329,330,332,333,336,338,339] }
    ]},
    { grupo: '🏠 EL HOGAR CRISTIANO', color: '#fd79a8', cats: [
        { nombre: 'El Hogar y la Familia', ico: '🏠', nums: [590,591,593] },
        { nombre: 'La Boda', ico: '💍', nums: [589] },
        { nombre: 'Los Niños', ico: '👶', nums: [119,120,598,599,600,601,602,603,604] }
    ]},
    { grupo: '🎗️ OCASIONES ESPECIALES', color: '#636e72', cats: [
        { nombre: 'Funeral', ico: '🕊️', nums: [588] }
    ]}
];

// ═══════════════════════════════════════════════════════
// 🎵 OVERLAY: Buscador de Himnos por Categoría
// ═══════════════════════════════════════════════════════
function abrirHimnarioCategorias() {
    var ov = document.getElementById('himnario-cat-overlay');
    if (ov) ov.remove();
    ov = document.createElement('div');
    ov.id = 'himnario-cat-overlay';
    ov.style.cssText = 'position:fixed;top:0;left:0;width:100%;height:100%;background:#0F172A;z-index:50000;overflow-y:auto;padding:20px;box-sizing:border-box;animation:devFadeIn 0.3s ease-out;';
    var h = '<div style="max-width:500px;margin:0 auto;">';
    // Botón volver
    h += '<button onclick="document.getElementById(\'himnario-cat-overlay\').remove()" style="display:flex;align-items:center;gap:10px;background:rgba(255,255,255,0.07);border:1.5px solid rgba(162,155,254,0.3);color:#fff;padding:10px 16px;border-radius:14px;cursor:pointer;font-weight:800;font-size:0.85rem;margin-bottom:16px;width:100%;"><span style="color:#a29bfe;font-size:1.1rem">←</span> Volver</button>';
    // Header
    h += '<div style="text-align:center;margin-bottom:20px;">';
    h += '<div style="font-size:2.5rem;margin-bottom:6px;">🎵</div>';
    h += '<h2 style="color:#a29bfe;font-size:1.3rem;margin:0 0 4px;font-weight:900;letter-spacing:2px;">HIMNARIO POR CATEGORÍA</h2>';
    h += '<p style="color:rgba(255,255,255,0.35);font-size:0.72rem;">Encuentra el himno perfecto para cada parte del culto</p>';
    h += '</div>';
    // Buscador rápido
    h += '<div style="margin-bottom:16px;">';
    h += '<input id="himn-cat-buscar" type="text" placeholder="🔍 Buscar por nombre o número..." oninput="filtrarHimnosCat(this.value)" autocomplete="off" style="width:100%;padding:12px 16px;background:rgba(255,255,255,0.06);border:1.5px solid rgba(162,155,254,0.3);color:#fff;border-radius:14px;font-size:0.9rem;outline:none;box-sizing:border-box;">';
    h += '<div id="himn-cat-resultados" style="display:none;margin-top:8px;"></div>';
    h += '</div>';
    // Categorías
    h += '<div id="himn-cat-grupos">';
    HIMNARIO_CATEGORIAS.forEach(function(grupo, gi) {
        h += '<div style="margin-bottom:16px;">';
        h += '<div style="color:' + grupo.color + ';font-weight:900;font-size:0.7rem;letter-spacing:2px;padding:8px 0;border-bottom:2px solid ' + grupo.color + '40;margin-bottom:10px;">' + grupo.grupo + '</div>';
        grupo.cats.forEach(function(cat, ci) {
            var totalH = cat.nums.length;
            h += '<div onclick="expandirCatHimno(' + gi + ',' + ci + ')" style="display:flex;align-items:center;gap:12px;padding:12px 14px;background:rgba(255,255,255,0.03);border:1px solid rgba(255,255,255,0.07);border-radius:14px;margin-bottom:6px;cursor:pointer;" id="himn-cat-' + gi + '-' + ci + '">';
            h += '<div style="font-size:1.3rem;">' + cat.ico + '</div>';
            h += '<div style="flex:1;"><div style="color:#fff;font-size:0.88rem;font-weight:800;">' + cat.nombre + '</div>';
            h += '<div style="color:rgba(255,255,255,0.3);font-size:0.65rem;margin-top:1px;">' + totalH + ' himno' + (totalH > 1 ? 's' : '') + '</div></div>';
            h += '<div style="color:rgba(255,255,255,0.2);font-size:1rem;">›</div>';
            h += '</div>';
            h += '<div id="himn-exp-' + gi + '-' + ci + '" style="display:none;padding:0 8px 8px;"></div>';
        });
        h += '</div>';
    });
    h += '</div></div>';
    ov.innerHTML = h;
    document.body.appendChild(ov);
    history.pushState({ overlay: 'himnario-cat' }, '');
}

function expandirCatHimno(gi, ci) {
    var el = document.getElementById('himn-exp-' + gi + '-' + ci);
    if (!el) return;
    if (el.style.display !== 'none') { el.style.display = 'none'; return; }
    // Cerrar otros
    document.querySelectorAll('[id^="himn-exp-"]').forEach(function(x) { x.style.display = 'none'; });
    var cat = HIMNARIO_CATEGORIAS[gi].cats[ci];
    var col = HIMNARIO_CATEGORIAS[gi].color;
    var h = '<div style="display:grid;gap:4px;margin-top:6px;">';
    cat.nums.forEach(function(num) {
        var titulo = HIMNARIO_ADVENTISTA[num] || 'Himno ' + num;
        h += '<div style="display:flex;align-items:center;gap:10px;padding:10px 12px;background:rgba(255,255,255,0.04);border-radius:10px;border-left:3px solid ' + col + ';">';
        h += '<div style="color:' + col + ';font-size:0.85rem;font-weight:900;min-width:32px;text-align:center;">' + num + '</div>';
        h += '<div style="color:#fff;font-size:0.82rem;font-weight:600;flex:1;">' + titulo + '</div>';
        h += '</div>';
    });
    h += '</div>';
    el.innerHTML = h;
    el.style.display = 'block';
    el.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
}

function filtrarHimnosCat(texto) {
    var res = document.getElementById('himn-cat-resultados');
    var grupos = document.getElementById('himn-cat-grupos');
    if (!texto || texto.length < 2) { res.style.display = 'none'; grupos.style.display = 'block'; return; }
    grupos.style.display = 'none'; res.style.display = 'block';
    var t = texto.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    var esNum = /^\d+$/.test(texto.trim());
    var encontrados = [];
    Object.entries(HIMNARIO_ADVENTISTA).forEach(function(e) {
        var num = parseInt(e[0]), titulo = e[1];
        var tNorm = titulo.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
        if (esNum ? num.toString().startsWith(texto.trim()) : tNorm.includes(t)) {
            // Buscar categoría
            var catNombre = '';
            HIMNARIO_CATEGORIAS.forEach(function(g) { g.cats.forEach(function(c) { if (c.nums.includes(num)) catNombre = c.nombre; }); });
            encontrados.push({ num: num, titulo: titulo, cat: catNombre });
        }
    });
    if (encontrados.length === 0) {
        res.innerHTML = '<div style="text-align:center;color:rgba(255,255,255,0.4);padding:20px;font-size:0.85rem;">Sin resultados</div>';
    } else {
        var h = '<div style="display:grid;gap:4px;">';
        encontrados.slice(0, 20).forEach(function(r) {
            h += '<div style="display:flex;align-items:center;gap:10px;padding:10px 12px;background:rgba(255,255,255,0.04);border-radius:10px;border-left:3px solid #a29bfe;">';
            h += '<div style="color:#a29bfe;font-size:0.85rem;font-weight:900;min-width:32px;text-align:center;">' + r.num + '</div>';
            h += '<div style="flex:1;"><div style="color:#fff;font-size:0.82rem;font-weight:600;">' + r.titulo + '</div>';
            if (r.cat) h += '<div style="color:rgba(255,255,255,0.3);font-size:0.6rem;margin-top:1px;">' + r.cat + '</div>';
            h += '</div></div>';
        });
        h += '</div>';
        if (encontrados.length > 20) h += '<div style="text-align:center;color:rgba(255,255,255,0.3);font-size:0.7rem;margin-top:8px;">...y ' + (encontrados.length - 20) + ' más</div>';
        res.innerHTML = h;
    }
}

