// BANCO TRIVIA — PARTE 3: CITAS + DOCTRINA E HISTORIA ADVENTISTA
// Legado Bíblico | Director: Jose
const TRIVIA_BANCO_P3 = {

    '¿Quién lo dijo?': {
        facil: [
            { p: "¿Quién dijo: 'Yo soy el camino, y la verdad, y la vida'?", o: ["Pablo", "Moisés", "Jesús"], c: 2, exp: "Jesús, en Juan 14:6." },
            { p: "¿Quién dijo: 'Aquí estoy, envíame a mí'?", o: ["Isaías", "Jeremías", "Jonas"], c: 0, exp: "Isaías respondió al llamado de Dios en el templo. (Isaías 6:8)" },
            { p: "¿Quién dijo: 'Señor, sálvame que perezco'?", o: ["Pedro", "Juan", "Judas"], c: 0, exp: "Pedro gritó esto mientras se hundía en el agua. (Mateo 14:30)" },
            { p: "¿Quién dijo: 'Dejad a los niños venir a mí'?", o: ["María", "Jesús", "Juan el Bautista"], c: 1, exp: "Jesús lo dijo cuando los discípulos querían apartarlos. (Marcos 10:14)" },
            { p: "¿Quién dijo: 'Señor, si eres tú, manda que yo vaya a ti sobre las aguas'?", o: ["Tomás", "Andrés", "Pedro"], c: 2, exp: "El atrevimiento de Pedro antes de caminar sobre el agua. (Mateo 14:28)" },
            { p: "¿Quién dijo: '¿Dónde está tu hermano Abel?'?", o: ["Adán", "Eva", "Dios"], c: 2, exp: "Dios le preguntó a Caín después del asesinato. (Génesis 4:9)" },
            { p: "¿Quién dijo: 'Amigo, ¿a qué vienes?'?", o: ["Pilato", "Jesús", "Marta"], c: 1, exp: "Jesús le dijo esto a Judas cuando lo traicionó. (Mateo 26:50)" },
            { p: "¿Quién dijo: 'Consumado es'?", o: ["Pablo", "Jesús", "Juan"], c: 1, exp: "Las últimas palabras de victoria de Jesús en la cruz. (Juan 19:30)" },
            { p: "¿Quién dijo: 'Tú eres el Cristo, el Hijo del Dios viviente'?", o: ["Juan", "Pedro", "Nicodemo"], c: 1, exp: "La gran confesión de fe de Pedro. (Mateo 16:16)" },
            { p: "¿Quién dijo: 'No solo de pan vivirá el hombre'?", o: ["Moisés y Jesús", "David", "Salomón"], c: 0, exp: "Moisés en Deuteronomio 8:3, y Jesús al ser tentado." },
            { p: "¿Quién dijo: 'Padre, perdónalos, porque no saben lo que hacen'?", o: ["Esteban", "Jesús", "Ambos"], c: 1, exp: "Palabras de Jesús crucificado. (Lucas 23:34)" },
            { p: "¿Quién dijo: 'Yo soy el buen pastor'?", o: ["David", "Jesús", "Salomón"], c: 1, exp: "Jesús da su vida por las ovejas. (Juan 10:11)" },
            { p: "¿Quién dijo: 'No te dejaré, hasta que me bendigas'?", o: ["Abraham", "Jacob", "Moisés"], c: 1, exp: "Jacob luchando con el Ángel en Peniel. (Génesis 32:26)" },
            { p: "¿Quién dijo: 'Señor, no soy digno de que entres bajo mi techo'?", o: ["Zaqueo", "El centurión romano", "Pedro"], c: 1, exp: "El centurión que pedía sanidad para su siervo. (Mateo 8:8)" }
        ],
        intermedio: [
            { p: "¿Quién dijo: 'Tu pueblo será mi pueblo, y tu Dios mi Dios'?", o: ["Orfa", "Rut", "Ester"], c: 1, exp: "Rut, la moabita, a su suegra Noemí. (Rut 1:16)" },
            { p: "¿Quién dijo: 'Jehová dio, y Jehová quitó; sea el nombre de Jehová bendito'?", o: ["David", "Job", "Salomón"], c: 1, exp: "Job al perder todo lo que tenía. (Job 1:21)" },
            { p: "¿Quién dijo: 'Habla, porque tu siervo oye'?", o: ["Moisés", "Samuel", "Jeremías"], c: 1, exp: "El niño Samuel al escuchar la voz de Dios. (1 Samuel 3:10)" },
            { p: "¿Quién dijo: '¿Quién soy yo para que vaya a Faraón?'?", o: ["Gedeón", "Moisés", "Amós"], c: 1, exp: "Moisés excusándose ante la zarza ardiente. (Éxodo 3:11)" },
            { p: "¿Quién dijo: 'Es necesario obedecer a Dios antes que a los hombres'?", o: ["Pedro y los apóstoles", "Pablo", "Esteban"], c: 0, exp: "Ante el concilio que les prohibía predicar. (Hechos 5:29)" },
            { p: "¿Quién dijo: 'Si perezco, que perezca'?", o: ["Ester", "Débora", "Jael"], c: 0, exp: "Ester antes de presentarse al rey Asuero sin ser llamada. (Ester 4:16)" },
            { p: "¿Quién dijo: 'He aquí el Cordero de Dios, que quita el pecado del mundo'?", o: ["Juan el Bautista", "Pedro", "El centurión"], c: 0, exp: "Juan al ver a Jesús venir hacia él. (Juan 1:29)" },
            { p: "¿Quién dijo: 'Casi me persuades a ser cristiano'?", o: ["Félix", "Agripa", "Galeón"], c: 1, exp: "El rey Agripa escuchando la defensa de Pablo. (Hechos 26:28)" },
            { p: "¿Quién dijo: 'Para mí el vivir es Cristo, y el morir es ganancia'?", o: ["Pablo", "Pedro", "Juan"], c: 0, exp: "Pablo escribiendo a los filipenses. (Filipenses 1:21)" },
            { p: "¿Quién dijo: 'Yo sé que mi Redentor vive'?", o: ["Ezequías", "David", "Job"], c: 2, exp: "Job en medio de su sufrimiento y llagas. (Job 19:25)" },
            { p: "¿Quién dijo: 'Señor, no les tomes en cuenta este pecado'?", o: ["Esteban", "Jesús", "María"], c: 0, exp: "Esteban, el primer mártir, mientras lo apedreaban. (Hechos 7:60)" },
            { p: "¿Quién dijo: '¿Puede acaso salir algo bueno de Nazaret?'?", o: ["Tomás", "Natanael", "Felipe"], c: 1, exp: "Natanael al oír hablar de Jesús por primera vez. (Juan 1:46)" },
            { p: "¿Quién dijo: 'Señor mío, y Dios mío'?", o: ["Tomás", "Pedro", "Zaqueo"], c: 0, exp: "Tomás al ver las marcas en las manos de Cristo resucitado. (Juan 20:28)" }
        ],
        avanzado: [
            { p: "¿Quién le dijo a David: 'Tú eres aquel hombre'?", o: ["Elías", "Natán", "Samuel"], c: 1, exp: "Natán al reprender a David por el pecado con Betsabé. (2 Samuel 12:7)" },
            { p: "¿Quién dijo: '¿No sabéis que los que corren en el estadio, todos a la verdad corren, pero uno solo se lleva el premio?'?", o: ["Pedro", "Jesús", "Pablo"], c: 2, exp: "Pablo ejemplificando la vida cristiana a los Corintios. (1 Corintios 9:24)" },
            { p: "¿Quién dijo: '¿Soy yo perro, para que vengas a mí con palos?'?", o: ["Saúl a David", "Goliat a David", "Simei a David"], c: 1, exp: "El gigante Goliat al ver al joven pastor. (1 Samuel 17:43)" },
            { p: "¿Quién dijo: '¡Hasta cuándo claudicaréis vosotros entre dos pensamientos?'?", o: ["Elías", "Moisés", "Josué"], c: 0, exp: "Elías en el Carmelo desafiando al pueblo de Israel. (1 Reyes 18:21)" },
            { p: "¿Quién dijo: 'Si ahora me matas, yo te ruego que me borres de tu libro que has escrito'?", o: ["Moisés", "Jeremías", "Pablo"], c: 0, exp: "Moisés intercediendo por el pueblo tras el becerro de oro. (Éxodo 32:32)" },
            { p: "¿Quién dijo: 'Mi castigo es mayor de lo que puedo soportar'?", o: ["Saúl", "Caín", "Judas"], c: 1, exp: "Caín tras ser desterrado por matar a Abel. (Génesis 4:13)" },
            { p: "¿Quién dijo: '¡He aquí, veo los cielos abiertos, y al Hijo del Hombre que está a la diestra de Dios!'?", o: ["Juan de Patmos", "Esteban", "Pedro"], c: 1, exp: "Esteban en visión antes de morir mártir. (Hechos 7:56)" },
            { p: "¿Quién dijo: 'Entristecido está mi espíritu, como para la muerte'?", o: ["Jesús", "Pablo", "Jonás"], c: 0, exp: "Jesús en el Getsemaní a sus tres discípulos más cercanos. (Mateo 26:38)" },
            { p: "¿Quién dijo: 'Esforzaos, y seamos hombres por nuestro pueblo'?", o: ["Joab", "David", "Josué"], c: 0, exp: "El comandante Joab antes de luchar contra amonitas y sirios. (2 Samuel 10:12)" },
            { p: "¿Quién dijo: 'Dejadlo que maldiga, pues Jehová se lo ha dicho'?", o: ["Saúl sobre David", "David sobre Simei", "Moisés sobre Coré"], c: 1, exp: "David soportando los insultos mientras huía de Absalón. (2 Samuel 16:10)" },
            { p: "¿Quién dijo: 'Danos hoy nuestro pan de cada día'?", o: ["La viuda a Elías", "Jesús enseñando a orar", "El pueblo a Jesús"], c: 1, exp: "Parte del Padre Nuestro. (Mateo 6:11)" },
            { p: "¿Quién dijo: 'Desierto, desierto he hecho... para el SEÑOR de los ejércitos'?", o: ["Elías", "Oseas", "Jeremías"], c: 0, exp: "Celo por la obra, dicho en la cueva. (1 Reyes 19:10)" },
            { p: "¿Quién dijo: 'Hoy ha llegado la salvación a esta casa...'?", o: ["Jesús en casa de Zaqueo", "Jesús en casa de Jairo", "Pedro a Cornelio"], c: 0, exp: "Cuando el publicano restituyó sus bienes. (Lucas 19:9)" }
        ]
    },

    /* ========================================================== */
    /* SECCIÓN ESPECIAL — SOLO IGLESIA ADVENTISTA (DOCTRINA/HISTORIA) */

    'Doctrina Adventista': {
        facil: [
            { p: "¿Cuál es el día de reposo según el 4to mandamiento?", o: ["El primer día (Domingo)", "El sexto día (Viernes)", "El séptimo día (Sábado)"], c: 2, exp: "El Sábado sigue siendo el día bendecido y santificado por Dios desde el Edén. (Éxodo 20:8)" },
            { p: "¿Qué significa la palabra 'Adventista'?", o: ["Que guarda el sábado", "Que espera la Segunda Venida (Advenimiento) de Jesús", "Que cree en los 10 mandamientos"], c: 1, exp: "'Adventista' viene de 'advenimiento', la promesa de que Cristo volverá en las nubes." },
            { p: "¿Qué creemos acerca del estado de los muertos?", o: ["Están como dormidos, inconscientes hasta la resurrección", "Van directo al cielo o al infierno", "Son fantasmas o espíritus guardianes"], c: 0, exp: "La Biblia compara la muerte con un sueño sin consciencia. (Eclesiastés 9:5)" },
            { p: "¿Cómo regresará Jesús a la tierra por segunda vez?", o: ["En forma espiritual e invisible al corazón", "De forma literal, visible y con la voz del Arcángel", "Ya regresó en forma de paz mundial"], c: 1, exp: "Todo ojo le verá sobre las nubes, no será en secreto. (Apocalipsis 1:7)" },
            { p: "¿Cuál es la norma o regla de fe para los adventistas?", o: ["Los escritos de Elena G. de White", "Exclusivamente la Biblia (Sola Scriptura)", "La tradición de los pioneros"], c: 1, exp: "La Biblia es nuestra única regla inerrante de fe y práctica." },
            { p: "¿Qué enseñamos sobre nuestro cuerpo (El cuerpo como templo)?", o: ["Se prohíbe comer alimentos inmundos (cerdo, etc) y sustancias dañinas porque es templo del Espíritu", "Solo importa el alma, el cuerpo no es tan espiritual", "Solo hay que ser vegetarianos obligatoriamente"], c: 0, exp: "1 Corintios 6:19 enseña que nuestro cuerpo es templo del Espíritu Santo." },
            { p: "¿Cómo debemos diezmar según la doctrina adventista?", o: ["Dar el 20% más las ofrendas", "Devolver la décima parte (10%) de nuestros ingresos a Dios", "Dar lo que sobre a fin de mes"], c: 1, exp: "El 10% de nuestras ganancias es santo para el Señor. (Malaquías 3:10)" },
            { p: "¿Qué evento profético central comenzó el 22 de Octubre de 1844?", o: ["El fin del mundo", "El Juicio Investigador en el santuario celestial", "La redacción del libro del Apocalipsis"], c: 1, exp: "Jesús pasó del lugar santo al lugar santísimo, cumpliendo Daniel 8:14." },
            { p: "¿Cuál de estos NO es parte del Mensaje de los Tres Ángeles de Apocalipsis 14?", o: ["Temed a Dios y dadle gloria", "Ha caído la gran Babilonia", "La obligación de guardar las fiestas solemnes de Israel"], c: 2, exp: "Las fiestas judías de sombras prefiguraban a Cristo y cesaron en la cruz." },
            { p: "¿Qué ocurrirá durante el Milenio de Apocalipsis 20?", o: ["Toda la tierra estará en paz habitada por los santos", "La tierra estará desolada, los santos en el cielo y Satanás atado aquí", "Será un segundo tiempo extra para que los pecadores se arrepientan"], c: 1, exp: "Milenio: los santos juzgan en el cielo y la tierra queda como abismo para Satanás." },
            { p: "¿Quién ejerce el ministerio de Sumo Sacerdote hoy por nosotros en el santuario celestial?", o: ["El Papa", "El pastor de la iglesia local", "Jesucristo"], c: 2, exp: "Tenemos un gran sumo sacerdote que traspasó los cielos: Jesús. (Hebreos 4:14)" },
            { p: "¿Creemos en un infierno donde la gente se quema por toda la eternidad sin morir jamás?", o: ["No. Los impíos son consumidos hasta dejar de existir (muerte segunda)", "Sí, es justicia divina eterna", "Creemos en el purgatorio temporal"], c: 0, exp: "\"La paga del pecado es muerte\" no vida eterna sufriendo. El fuego los consume por completo." },
            { p: "¿Qué tipo de bautismo enseña la Iglesia Adventista?", o: ["Rociar agua en la frente de bebés", "Bautismo por inmersión completa de personas que creen y se arrepienten", "Cualquiera de los dos es correcto según su iglesia"], c: 1, exp: "Bautismo (del griego 'sumergir') es el sepultamiento del viejo hombre en agua." },
            { p: "¿Para qué se instituyó originalmente el casamiento bíblico como doctrina?", o: ["Cualquier pareja que se ame", "Exclusivamente para un hombre y una mujer en una unión de por vida instituida en Edén", "No hay un modelo específico en la iglesia"], c: 1, exp: "El matrimonio es un pacto sagrado entre un hombre y una mujer. (Génesis 2:24)" }
        ],
        intermedio: [
            { p: "¿Cuál de las siguientes es una señal bíblica distintiva de la 'Iglesia Remanente' según Apocalipsis 12:17?", o: ["Tener un gran templo físico y poder político", "Hablar en lenguas y milagros de sanidad masivos", "Guardar los mandamientos de Dios y tener el testimonio de Jesús"], c: 2, exp: "La iglesia remanente debe tener la fe de Jesús y guardar su ley (incluyendo el sábado)." },
            { p: "¿Qué es o quién tiene el 'Testimonio de Jesús' mencionado en Apocalipsis 19:10?", o: ["El don de Milagros", "El don del Espíritu de Profecía", "El don de Lenguas angélicas"], c: 1, exp: "El ángel declara: 'El testimonio de Jesús es el espíritu de la profecía.'" },
            { p: "¿Quién creemos que ordenó cambiar el sábado por el domingo a través de la historia (Daniel 7:25)?", o: ["Jesús lo cambió en su resurrección", "El poder representado por el 'cuerno pequeño' (El papado de Roma)", "El apóstol Pablo en sus cartas a los gentiles"], c: 1, exp: "El cuerno pequeño, profetizado por Daniel, 'pensaría en cambiar los tiempos y la ley'." },
            { p: "¿Qué representa la 'Marca de la Bestia' proféticamente?", o: ["Un chip físico o microchip en la mano", "Un código de barras o tatuaje en la frente (666)", "La obediencia forzada a una ley dominical falsa en oposición a la Ley de Dios"], c: 2, exp: "La marca se opone al Sello de Dios (el sábado) como asunto final de adoración." },
            { p: "¿En qué época cree la doctrina adventista que estamos ahora proféticamente?", o: ["Tiatira", "Tiempo de angustia previo a las plagas", "La iglesia laodicense y el tiempo del Juicio Investigador"], c: 2, exp: "Vivimos en el último paralelo profético: el juicio antes que Cristo regrese." },
            { p: "La ley de Dios se divide históricamente en dos partes. ¿Cuál fue abolida en la cruz?", o: ["Los Diez Mandamientos que traían el ministerio de muerte", "La ley ceremonial de ritos, sacrificios animales y sombras de Jesús", "Todas fueron abolidas; estamos solo bajo la gracia"], c: 1, exp: "Las ceremonias apuntaban al Cordero (Jesús) y perdieron su propósito al morir Él." },
            { p: "¿Qué papel juegan las obras en la salvación según el credo adventista?", o: ["Somos salvos por la gracia SOLAMENTE, y las obras son el FRUTO natural de un corazón salvo", "La fe nos salva en un 50% y nuestras buenas obras nos aseguran el otro 50%", "Las obras y guardar el sábado te ganan el cielo"], c: 0, exp: "Nadie se salva por guardar la ley, pero el que es salvo guarda la ley por amor. (Efesios 2:8-10)" },
            { p: "Acerca del Santuario Celestial: ¿Cuándo intercedía el sumo sacerdote en el 'Lugar Santísimo' en el AT?", o: ["Todos los días del año con la sangre diaria", "Solamente un día al año (El Día de la Expiación)", "Solamente en la pascua cuando cordero moría"], c: 1, exp: "Esto ilustra que Cristo entró en la fase de juicio en su ministerio intercesor final." },
            { p: "¿Por qué se lavan los pies antes de participar de la Santa Cena?", o: ["Para limpiar los pies de forma literal antes del pan puro", "Es un rito introducido por Elena de White", "Como símbolo de humildad renaciendo, mandado por Cristo en Juan 13"], c: 2, exp: "El rito de humildad limpia las faltas cotidianas y une en amor a los hermanos." },
            { p: "¿Cómo ven los adventistas el uso de joyas, anillos y maquillaje llamativo?", o: ["Lo prohíbe salvíficamente, irán al infierno", "Fomenta la modestia cristiana y la belleza interior por sobre el adorno exterior ruidoso (Pedro 3:3)", "Se recomienda usarlo solo en bodas adventistas y fotos"], c: 1, exp: "El principio es ser luz por carácter, modestia y sencillez profana." },
            { p: "En el Santuario, ¿qué representa la mesa de los panes de la proposición?", o: ["El cuerpo de Jesús y que Él es el Pan de Vida sosteniendo a su pueblo", "La provisión material que Dios siempre envía al pastor", "Que los sacerdotes jamás pasen hambre física al oficiar"], c: 0, exp: "Las 12 tortas apuntaban a Jesús alimentando y sosteniendo a las 12 tribus permanentemente." },
            { p: "¿Quién es considerado nuestro Creador directo y cómo se formó la tierra? (Doctrina de la Creación)", o: ["Jesucristo como agente creador divino, en seis días literales (no evolución)", "Dios de forma espiritual creando por medio de explosiones y milenios evolutivos (Diseño inteligente mixto)", "Solo Dios Padre; Jesús es una criatura más"], c: 0, exp: "Todo fue hecho por la Palabra creadora: Cristo, manifestándose como un todo literal de semanas reales." },
            { p: "¿Existe una guerra invisible (El Gran Conflicto)? ¿Entre quiénes comenzó?", o: ["Cielo vs Infierno, desde antes de la creación", "Entre Cristo (Miguel) y Satanás (Lucero) por el carácter y la ley de Dios dentro del cielo primero", "Entre Adán y Eva por comer el fruto de la rebelión terrenal"], c: 1, exp: "Inició en el cielo como controversia y se trasladó a este globo tras la caída del ser humano." }
        ],
        avanzado: [
            { p: "Aparte de Apocalipsis 14 (Los Tres Ángeles), ¿qué 'ángel' o mensaje une fuerzas en un gran clamor final profético?", o: ["El cuarto ángel de Apocalipsis 18 que alumbra la tierra con su gloria", "El sexto ángel del secamiento del Eufrates y la batalla de reyes", "El ángel fuerte del libro abierto de Apocalipsis 10 anunciando tiempo ya"], c: 0, exp: "El clamor es: 'Salid de ella, pueblo mío' potenciando la amonestación final al orbe." },
            { p: "¿Sobre qué base teológica el Juicio Investigador en 1844 concuerda con Daniel 8 y Daniel 9 juntos?", o: ["Porque el cuerno pequeño en Daniel 8 profanaría pero el capítulo 9 confirma el pacto general del pueblo y la sanación en Roma", "Daniel 9 da la fecha de inicio del bloque de las 70 semanas (457 a.C.), que es además el punto de inicio de la línea larga de Daniel 8 de los 2300 días", "Eran dos visiones separadas, se unieron metafóricamente después del gran chasco por Elena.G.White"], c: 1, exp: "El ángel Gabriel interrumpe en el cap 8 y en el 9 le explica el corte (70 semanas) decretadas del inicio general de 2300 días." },
            { p: "¿Dónde dice la Biblia que Jesús es el Arcángel Miguel?", o: ["Se infiere porque Miguel significa 'El que es como Dios' y su voz resucita muertos en Tesalonicenses y Judas", "Literalmente dice en Apocalipsis 'Miguel el Cristo de Dios' de forma explícita", "En verdad, la denominación adventista enseña que Miguel es solo un ángel fuerte no divino que peleó con Satanás y la cruz por nosotros (doctrina rebajada)"], c: 0, exp: "Miguel (Jefe de Ángeles, Jesús el líder militar de cielo) es el preencarnado, y reprende a Satanás sobre Moisés." },
            { p: "¿Qué relación hay entre el Sellamiento de los 144,000 y los Cuatro Ángeles que detienen los vientos?", o: ["Están en guerra intentando de que no caiga el gran juicio y la tormenta literal final pero fallarán", "La obra de gracia no cesará hasta que el carácter de Dios esté formado y sellado plenamente (sábado en mente) de Su pueblo listos para estar parados sin intercesor luego", "Solo los mártires fieles a la primera venida formaran esos catorce millones estáticos"], c: 1, exp: "'No dañéis... hasta que hayamos sellado a los siervos' (Ap. 7:3). Los vientos son conmociones y destrucción final controlada." },
            { p: "Doctrina de la Expiación: ¿Se completó total y definitivamente TODO acto expiatorio en la cruz del calvario el viernes?", o: ["Totalmente, no se requiere más ministerio porque Él pagó consumado la raza fue salva incondicionalmente todos los creyentes el mismo día y no hay juicio intercesor en pie sobre lo divino de la culpa humana", "El pago de sangre expiatoria (sacrificio) fue completado y perfecto en la cruz. Pero la APLICACIÓN investigativa e intercesora del santuario se perfecciona y sigue ministrándose en el cielo (Santuario) como el AT con la sangre borrando en yom kippur.", "Cristo todavía sufre de cruz la salvación y el ministerio del pan continuará por sacrificio milenial."], c: 1, exp: "La provisión expiatoria es completa, pero la obra final de sumo sacerdote aplica y borra de los registros la culpa investigada." },
            { p: "¿Tiene el rebaño profético final algo que lo liga con la amonestación para 'adorar al que hizo el cielo, mar... y fuentes' de Apocalipsis 14:7?", o: ["Esa cita teológica repite la base textual del cuarto mandamiento del reposo Sabático. Vinculando fuertemente el sábado y creación.", "Trata sobre no tomar nombres e imágenes del santuario católico de mar o fuente idolatra.", "Es una predicación ecológica global de cuidar a la 'Creación madre tierra y las fuentes que es la Pachamama moderna' antes del Apocalipsis natural de azufre del último siglo."], c: 0, exp: "'Adorar al creador'. Evoca textual al sábado: Éxodo 20:11 'En 6 días hizo Jehová los cielos, tierra y las fuentes'." },
            { p: "Simbólicamente ¿qué quiere arrancar la Reforma de Salud promovida como doctrina distintiva para el tiempo del fin adventista? y no solo ser una dieta dietética particular", o: ["Ser los más sanos deportivos fuertes estéticamente frente al mundo enfermo moderno como muestra elitista general sana.", "Restaurar un sistema biológico óptimo para discernir claramente los embates del enemigo y mensajes divinos finos, protegiendo al Espíritu y cerebro ante el último tiempo de gracia (Preparación espiritual y vida consagrada mente fuerte templanza).", "Vender alimentos especiales en ferias o comercios al mundo global ganando en dinero por monopolio vegetal exclusivista a la bestia de la ciencia natural"], c: 1, exp: "Es el 'Brazo derecho' del evangelio. La pureza de mente va ligada al discernimiento claro y victoria espiritual templada de la naturaleza corporal caída al pecar para poder pasar la prueba y sello final del fin inmaculado y en santificación continua total integral de mente alma." },
            { p: "¿Quiénes de entre los impíos experimentarán la 'Segunda Muerte' de la que habla el lago de fuego en la base doctrinal?", o: ["Solo los impíos que cayeron en el tiempo de gracia final y no los de los siglos mileniales oscuros porque a esos ya quemó Dios el infierno del alma, pero Satanas ahora sufrira tormento eternal y final de todos esos como lider demoniaco la segunda vez.", "Todos aquellos humanos junto con ángeles caídos y satanás que rechacen la obra mesiánica. Los devorará el fuego hasta dejar raíz ni rama convirtiéndose en ceniza aniquilación de por el resto eterno cesando de sentir (Ezequiel).", "Solo los ángeles satánicos serán quemados completamente destruidos aniquilación pero los humanos gozaran purificación eterna"], c: 1, exp: "Serán convertidos en 'estopa' es aniquilacionismo puro. El salarios es cesación absoluta eterna del alma destructible en el abismo ardiente limpiador." }
        ]
    },

    'Historia Adventista': {
        facil: [
            { p: "¿Quién fue el predicador bautista que estudió las profecías y anunció que Jesús volvía en 1844?", o: ["José Bates", "Guillermo Miller", "Jaime White"], c: 1, exp: "Guillermo Miller estudió Daniel 8:14 y lideró el movimiento 'Millerista' que anunció erróneamente el fin del mundo para esa fecha histórica fundamental americana profetizada pero desilusionante antes que nazca luz." },
            { p: "¿Qué se conoce mundialmente por los adventistas como el 'Gran Chasco'?", o: ["Cuando las iglesias rechazaron el mensaje de sábado a los primeros guardadores.", "El 22 de octubre de 1844, cuando Jesús no regresó a la tierra como ellos habían calculado en las profecías y amaneció de forma terrenal natural desilusionando a miles de piadosos que esperaban los cielos abrirse gloriosos.", "La pérdida en naufragio de los primeros misioneros y folletos mandados con fuego divino y chasco para la obra de impresión que White vio que quemaron satanás temprano"], c: 1, exp: "Esperaban el fin. Jesús no volvió, pero lloraron hasta el amanecer; de esa amarga noche Dios despertó de las cenizas la comprensión de la obra celestial investigando luz." },
            { p: "¿Cuál pionera tuvo visiones y profetizó guiando a la Iglesia Adventista (como la 'luz menor') por más de 70 años sin tener salud o intelecto de estudio en su infancia?", o: ["Rachel Oakes", "Raquel Preston", "Elena G. de White"], c: 2, exp: "Elena G. Harmon (White) recibió su primera visión y consolidó al movimiento del gran chasco uniéndolos a la Biblia y vida temperante en salud." },
            { p: "¿Cuál pionero antes capitán de mar fue el gran 'Apóstol del Sábado' que aceptó de parte de bautistas y la predicación adventista introduciendo el reposo de Dios?", o: ["Hiram Edson", "José Bates", "Urias Smith"], c: 1, exp: "Bates lo aceptó ferviente luego de estudiar folletos. Escribió tractados sobre sábado y gastó su dinero apoyando pioneros iniciales del día de Dios bíblico antes de Jaime White." },
            { p: "¿Qué pasó con Hiram Edson al caminar por un campo de maíz el día después del Gran Chasco del veintidos de octubre doloroso?", o: ["Satanás se le enfrento en visión directa diciéndole ríndete adventista tu Cristo no ha vuelto, pero lo derrotó Edson", "Dios le devolvió el maíz seco al verde demostrando promesa de santuario", "Tuvo la profunda revelación que aclaró el fallo de Miller: Jesús no venía a limpiar la tierra, sino al lugar santísimo del cielo como gran sumo pastor en juicio y día de expiación profético final inaugurándola, ¡resolviendo el dolor!. "], c: 2, exp: "Esa tremenda iluminación celestial y de estudio cambió todo. El santuario a purificar era arriba no abajo en mil novecientos y tantos en la cruz de luz general de fe." },
            { p: "¿Cómo se enteraron los primeros de que el sábado se debía cuidar del atardecer al atardecer basando en estudio metódico profundo de Biblia antigua no del vaticano?", o: ["Elena G de White en visión impidió comer cerdo el sexto día así nació y se completó revelando de sol a sol que debía prepararse", "J. N. Andrews descubrió en estudios estrictos bíblicos sobre reposos judío antiguo el concepto 'de tarde a tarde celebraréis el sábado', no de media noche a media noche horario romano."], c: 1, exp: "Andrews probó que el mediodía grecorromano era anti-bíblico y que 'cayó la tarde' marca el Génesis." }
        ],
        intermedio: [
            { p: "¿Quién fue el primer misionero oficial enviado al extranjero por la Iglesia (a Suiza en Europa 1874) abriendo la predicación moderna global mas allá de estados unidos base americana de obra pionera?", o: ["Urias Smith autor e ilustrador", "John Nevins Andrews (J. N. Andrews) el intelectual", "Stephen Haskell de Australia temprana"], c: 1, exp: "J.N Andrews. Entregó su vida literaria y el dolor de su esposa, el seminario de la iglesia mundial lleva su nombre como un líder estudioso que llevó fuego divino pionero. " },
            { p: "¿En qué año se organizó oficialmente la 'Iglesia Adventista del Séptimo Día' bajo ese nombre elegido por voto de hermanos en Michigan?", o: ["1844 en Washington NH con los Oakes hermanos", "1888 en Minneapolis en la gran sesión de justificación por fe y gracia", "1863 en Battle Creek, Michigan por los delegados"], c: 2, exp: "Luego de debatirlo para publicar libros unidos como misión global se formó legal para que nadie robara nombre propio del mensaje adventista y sabatista fundacional." },
            { p: "¿Qué publicación y folletería pionera famosa en la maleta comenzó Jaime White que daría a luz 'la gran imprenta adventista' como rayos de luz rodeando en fe la tierra?", o: ["La Revista The Present Truth (La Verdad Presente) luego Review and Herald mundial hoy", "The Signs of the Times en Australia tempranas", "Liberty Magazine del congreso"], c: 0, exp: "White publicaba sin fondos doblando a mano, luego se transformó en parte vital de la iglesia moderna Revista y Heraldo. Ella le profetizó: imprima rayitos, y circundaran el planeta hoy en lenguas fuego de gloria a Cristo y mensaje final verdadero" },
            { p: "¿Qué sucedió clavemente en el Congreso de Minneapolis en el grandioso y polémico año fundacional del mensaje 1888?", o: ["Jones y Waggoner presentaron fuerte y vital 'La Justificación por la Fe en Cristo', contrarrestando el legalismo guardador estricto pero vacío del adventismo seco pionero debatiendo la naturaleza vital mesiánica para ser parte de Cristo de verdad hoy", "Se cambió oficialmente el nombre del colegio de médicos de Kellogg y hubo incendio mundial allí que dolió la obra joven y al espiritismo fundacional", "Smith se peleó con White fuertemente abandonando su llamado profético por años en tristeza terrenal "], c: 0, exp: "Jones (Alonzo) y Waggoner re-despertaron a Cristo como ÚNICA esperanza en vez de la ley moral sola en salvaciones de carne muertas." }
        ],
        avanzado: [
            { p: "¿Quién compró una campanita pequeña con sus últimos centavos al lado de la carretera luego de cruzar un puente en el crudo invierno para animar su trabajo literario publicitario en favor al Sello de Dios?", o: ["Jaime White antes de enfermar de parálisis por escribir tanto", "El anciano Joseph Bates de New Bedford viajando frío con su gran fe y amor celestial al mensaje en nieves con un último centavo guardado que luego le triplicaron para correo salvando su impresión de sábado", "Hiram Edson vendiendo su granja para que los pioneros publiquen The Adventist Review fundacional"], c: 1, exp: "Bates es el líder de la temperancia heroica y sacrificado de la causa, este es popular cuento pionero de fe en frío invierno nevado" },
            { p: "¿Qué pionero famoso dejó finalmente la organización iglesia y el Espíritu de Profecía después del desastre panteísta del Sanatorio Médico de fama divina de Battle Creek en su caída médica mística inmensa en incendios?", o: ["Urias Smith el autor del gran libro explicativo sobre Daniel profeta ameno", "Jaime White por locura paralitica o rebeldía temprana del congreso viejo en canas blancas", "John Harvey Kellogg, que combinó medicina poderosa en cereales con panteísmo satánico en 'The Living Temple' falso y rebelión a la hermana White profetisa sobre dinero real "], c: 2, exp: "Kellogg (del cereal) fue expulsado pese a ser gran doctor por rebelar en fuego sobre enseñanzas no divinas (Dios adentro de las plantas). Su edificio gigante de sanatorio ardió sin control profetizado." },
            { p: "¿Quién era el joven afroamericano ('mulato') que recibió la primera visión profética, antes de que el manto pasara a Elena Harmon, pero se negó en humildad u obediencia miedo de publicarlo en racismo terrenal y luego lo lamentó mucho bajo el rechazo lloroso post-Millerista dolor eterno?", o: ["El pastor negro famoso de américa E. E. Cleveland", "William Foy de la iglesia unificada metodista joven miedosa de fama racial hostil de Boston del tiempo del fin que vio perlas ", "Hazen Foss, un hombre blanco intelectual que negó también o se demoró antes de las plagas en Maine en temor del chasco dolor"], c: 1, exp: "William Foy y Hazen Foss. Pero Foy era de raza negra americana la cual recibió dos visiones (que armonizan con EGW luego hermosamente en libros suyos de Boston tempranos en fe) pero él las contó limitadamente antes del traspaso a Ellen por temor raciales divinos en su dolor de la hora oscura del chasco millerista. Hazen lo rechazó todo mudo total divino de Dios." },
            { p: "¿Cómo fue la visión profética que inspiró la apertura de la vasta y divina Reforma Pro-Salud Adventista global en contra carne y mal vivir que se extendió desde el agua divina en hospitales grandiosos a continentes médicos en su sanatorio? ", o: ["Visión de 'Otsego' en 1863 en la casa Hilliard. Dios le abrió visión en oración, y se levantó débil sin fiebre entendiendo el tabaco, los venenos asados, tes negros y que el poder medicinal es luz natural agua templada de fe al paciente para evitar el pecado y mente sana adorativa vital", "Visión de 'Elmshaven' donde se dictó el The Living Temple falso de comida vegetariana en California pionera al final de muerte triste ", "En Battle Creek ella dictó el libro el Ministerio de Curación luego de comer carne podrida de un asado pionero y enfermar del estomago doliendo en cama enferma viendo su error profético personal"], c: 0, exp: "Otsego: la luz grande llegó en 45 minutos. Los pioneros comían hasta jabalí cerdo pionero oscuro y fumaban y aquí comenzó un gigante salto del adventismo a ser líder de curación sana hoy en el globo." },
            { p: "La Primera Sociedad de Tratados (Imprenta base global inicial moderna celular del adventista fuerte en casa vecina) inició pionera del chasco en que fe humilde e impresionante a la labor profética bajo el pastor S. N Haskell fundacionalmente liderando jóvenes y obreras mujeres:", o: ["Stephen N. Haskell lideró formando mujeres de la iglesia en las escuelas a leer para el presidente en Nueva York", "En South Lancaster, formó la 'Vigilant Missionary Society' con las 'pioneras en la sombra' (Mary Andrews joven y amigas) que escribian cartas oraban enviaban cajas de literaturas hasta las montañas europeas por el servicio postal sembrando la Review por el orbe joven encendiendo fuego", "F. D. Nichol la formuló en Takoma Park despues del incendio de Michigan como respuesta divina al chasco de los pioneros cansados literarios bajo tierra de fe y lagrimas "], c: 1, exp: "Haskell agrupó a mujeres fieles. De allí surge el departamento de Escuela Sabática y de Obra Personal de literaturas de puerta en puerta (colportaje y folleteria) en el heroico adventismo obrero escondido pero vital." }
        ]
    }

};
